name: Test Project
on: workflow_dispatch #push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          path: './my-app'
      - name: Install NodeJS
        uses: actions/setup-node@v4
        node-version-file: 'package.json'
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
        